### PR TITLE
Define OpenSLO spec as Go structs

### PR DESCRIPTION
**Pull request by kenfinnigan**
Can be an alternative to #20 and #87, or as a precursor to them.

Changes:
 - Moved `v1alpha` structs from oslo to here
 - Created `v1beta1` structs to represent the current state of the spec
 - Renamed api version from `v0.1.0-beta` to `v1beta` as the API version in the YAML has a different meaning to the particular release of the OpenSLO project, which can be `v0.1.0-beta` with an API version of `v1beta1`
 - Removed `Service` from `v1beta` as it is not used, as far as I could tell
 - Renamed `kind` to `type` for `AlertCondition` to prevent confusion with `Kind` which has a different meaning

### CODE REVIEW

**Comment by nieomylnieja** [comment]
hey @kenfinnigan, we're planning OpenSLO community meeting between 05-09 of February.
Feel free to vote in [this Slack survey](https://openslo.slack.com/archives/C0202J83M3R/p1706191817667639) or let me know which date suits you best here:
- 05.02 18:00 UTC (Monday)
- - 05.02 18:00 UTC (Monday)
- - 05.02 18:00 UTC (Monday)
- - 05.02 18:00 UTC (Monday)

**Comment by nieomylnieja** [comment]
hey @kenfinnigan, we're planning OpenSLO community meeting between 05-09 (Monday-Friday) of February, 18:00 UTC.
If you'd like to join and discuss your proposal, you can vote on the specific date in [this survey](https://openslo.slack.com/archives/C0202J83M3R/p1706191817667639), or let me know directly here.
We'll pick the date which will suit the most people and I'll let you know here once we've picked it :)

**Comment by kenfinnigan** [comment]
hey @nieomylnieja, I've not had the time for a while to participate in OpenSLO.

Fine with this branch being closed as things have likely changed a lot since I submitted it

**Comment by nieomylnieja** [comment]
hey @kenfinnigan, I'll close this one but I will use some parts of it to create a PR covering the same ground, thanks for the effort here!

**Pull request closed without merging**
