### PR TITLE
V2alpha1 Kubernetes compatibility

### PR DESCRIPTION
**Pull request by fourstepper**
Resolves https://github.com/OpenSLO/OpenSLO/issues/234

### CODE REVIEW

**Comment by fourstepper** [comment]
After a couple of hectic edits, I consider this ready now :)

**Comment by nieomylnieja** [comment]
hey @fourstepper, we're planning OpenSLO community meeting between 05-09 (Monday-Friday) of February, 18:00 UTC.
If you'd like to join and discuss your proposal, you can vote on the specific date in [this survey](https://openslo.slack.com/archives/C0202J83M3R/p1706191817667639), or let me know directly here.
Regardless of your attendance, we'll discuss the issue you've brought up and approve/request clarification/reject it afterwards.
We'll pick the date which will suit the most people and I'll let you know here once we've picked it :)

**Comment by Hy3n4** [comment]
I also voted for 5th. Although I don't know if I will be able to attend.

**Review by nieomylnieja — APPROVED** [review]
As discussed on our last community meeting (2024-02-05) we want to move towards full k8s CRD compatibility, this is the first crucial step. The proposal was approved.

@fourstepper there are some issues with Markdown formatting which the newest markdownlint-cli detects, can you fix them? Looks like your editor is using hard tabs.

**Comment by fourstepper** [comment]
@nieomylnieja I'm using `prettier` for Markdown, never heard of markdownlint, but I will take a look...

**Comment by fourstepper** [comment]
Fixed :)

Some loosely-related thoughts which could be subjective:

1. I would say `prettier` is pretty standardized for quite a few file types as a formatter. Perhaps we could use that instead? No real hard opinions though
2. I don't think the CI workflow should require approval... As we're an open-source project, CI comes free

**Comment by nieomylnieja** [comment]
1. I think it might be due to your prettier settings though, right? We could consider that too.
2. I don't know why was it set up this way, I'll check the settings and change them, I agree.

**Comment by fourstepper** [comment]
1. 🤷 I'm using the default config for Markdown, AFAIK
2. Nice! 🥳

**Pull request merged**
