### PR TITLE
add optional k/v labels to Objectives

### PR DESCRIPTION
**Pull request by BertHartm**
objectives section copied verbatim from existing spec https://github.com/OpenSLO/OpenSLO/blob/b54f77a7637f3822a12b19624c5899a038958f4f/README.md?plain=1#L263C1-L280C4, except for the addition of the labels object.

The driving use case is being able to categorize the objectives and associate them to processes or tools outside of the SLO itself. E.g. if there's a goal to improve an SLO Objective, it may want to be tagged with identifiers around that larger goal, but the existing objective may want to remain in place for existing alerting, etc.

### CODE REVIEW

**Comment by nieomylnieja** [comment]
hey @BertHartm, we're planning OpenSLO community meeting between 05-09 (Monday-Friday) of February, 18:00 UTC.
If you'd like to join and discuss your proposal, you can vote on the specific date in [this survey](https://openslo.slack.com/archives/C0202J83M3R/p1706191817667639), or let me know directly here.
Regardless of your attendance, we'll discuss the issue you've brought up and approve/request clarification/reject it afterwards.
We'll pick the date which will suit the most people and I'll let you know here once we've picked it :)

**Comment by BertHartm** [comment]
> hey @BertHartm, we're planning OpenSLO community meeting between 05-09 (Monday-Friday) of February, 18:00 UTC. If you'd like to join and discuss your proposal, you can vote on the specific date in [this survey](https://openslo.slack.com/archives/C0202J83M3R/p1706191817667639), or let me know directly here. Regardless of your attendance, we'll discuss the issue you've brought up and approve/request clarification/reject it afterwards. We'll pick the date which will suit the most people and I'll let you know here once we've picked it :)

Thanks for the heads up. Voted

**Review by nieomylnieja — APPROVED** [review]
On the [last community meeting](https://openslo.com/blog/openslo-project-meeting-february-2024/) we've agreed on merging this to v2alpha :) thanks a lot for this contribution!

Side note: We also decided to change the labels to adhere with k8s schema, but this will get done in a different PR.

**Comment by nieomylnieja** [comment]
@BertHartm can you fix the Markdown linter reported heading issue? Thanks :)

**Comment by BertHartm** [comment]
> @BertHartm can you fix the Markdown linter reported heading issue? Thanks :)

Updated, please review

**Review by weyert — APPROVED** [review]
Totally make sense to me

**Pull request merged**
