### PR TITLE
Define OpenSLO Spec as JSON-Schema

### PR DESCRIPTION
**Pull request by CRThaze**
# What

As an [outcome of discussions in the last OpenSLO community meeting](https://github.com/OpenSLO/OpenSLO/issues/124), and in part to enable https://github.com/OpenSLO/OpenSLO/issues/13, we are attempting to define the OpenSLO format in a computer-readable format; using JSON-Schema.

# Design Decisions

- The most commonly supported version of JSON-Schema is currently "draft-07". This is also the version required by Backstage should this JSON-Schema be used to teach Backstage how to ingest OpenSLO. Thus the Schema has been defined using that version.
- To keep things readable, I've opted to break up the schema definition into many files. However only the `openslo.schema.json` should need to be referenced when consuming this schema as it references all other files either directly, or indirectly.
- The Schema IDs were selected on the assumption that we will eventually host them under https://openslo.com/schemas/v1/  Though this will not affect the ability to consume these schema files locally; using a URL as the ID for a Schema document allows tools to automatically fetch schemas published to the internet.

## Intentionally Omitted Validations

- We define the valid values for timeZone to be any IANA Timezone name.  This is, however, not a completely static list (updates are made with some regularity) which presents a challenge for validation. I scraped the latest list of names from IANA's database and made a reusable enum for it, but we may want to decide if this is something that should be validated strictly by the spec, or if the validation logic should be off-loaded to Oslo (which might be able to query the current valid list) or if we want to leave that up to implementation and only validate that it looks like an IANA timezone.
- Some properties are required conditionally, based on the properties set in another referenced object. Specifically the op and value properties within the objectives. This will likely prove tough to validate within JSON-Schema, and would probably require some ugly logic, if it is even possible.  Now to me, this suggests that these properties actually belong to the SLI object and not the objective. But regardless, as it currently stands, that might also be something we will need to rely on Oslo to validate, as it cannot be expressed nicely with JSON-Schema (if at all).

# Testing

The validation of the schema is performed using the Go unit-test framework, written with a popular library that can ingest JSON-Schema documents, perform meta-validation on their formatting, and then use those schema documents to validate other documents.
I've taken the v1 test files and test cases from Oslo to use here. However in doing so I noticed a few discrepancies between those test files (used in the success cases) and what is defined in the spec. Mainly that names are defined in the v1 spec as only being lower-case, but many example files did not follow this. So I've made some changes to bring them fully in line with the v1 spec.

```bash
# Install schema testing dependencies
make install/checks/schema-validation
# Run validation
make run/checks/schema-validation
```

# Next Steps

- The schema validations are probably something we want to bring into the github pull-request workflows.
- The schema validation file provides an example of how simple it is to use JSON-Schema documents to do most (but not all) of the validations currently done by Oslo. Using the same strategy in the `schema-test/schema_test.go` file we could eventually make Oslo consume the JSON-Schema and eliminate a lot of existing validation logic.

### CODE REVIEW

**Review by ian-bartholomew — COMMENTED** [review]
This is great! Thank you @CRThaze !!

**Comment by proffalken** [comment]
@CRThaze looks great so far, there's a couple of spelling checks that are failing: 

https://github.com/OpenSLO/OpenSLO/runs/6406627728?check_suite_focus=true#step:7:15

**Comment by CRThaze** [comment]
@ian-bartholomew @proffalken PTAL

**Review by ian-bartholomew — APPROVED** [review]
This is great, thank you!!

**Comment by kenfinnigan** [comment]
It would be good to agree on https://github.com/OpenSLO/OpenSLO/issues/124 before merging work that may or may not be needed depending on the outcome.

I wouldn't want to see work merged and then removed because a different direction was decided.

**Pull request merged**
