### PR TITLE
allow for the inclusion of arbitrary key / value metadata

### PR DESCRIPTION
**Pull request by BertHartm**
When working with lots of SLO / SLI objects at scale, it can be helpful to be able to add arbitrary metadata to indicate things like:
- ownership
- association to certain projects
- criticality or other ways that teams might need to organize their SLOs, SLIs, and Datasources.

Allowing for key value pairs in the spec directly avoids having to do workarounds like depend on naming schemes.

### CODE REVIEW

**Comment by BertHartm** [comment]
Some prior discussion is in #179

I was unsure of the best syntax to indicate an optional object of keys with string values, so I grabbed this based on the k8s CRD spec, but if something else is preferred let me know.

**Comment by nieomylnieja** [comment]
@BertHartm you can open a separate PR for objectives' metadata, I think this suggestion also makes a lot of sense :)

**Comment by BertHartm** [comment]
> @BertHartm you can open a separate PR for objectives' metadata, I think this suggestion also makes a lot of sense :)

Thanks, filed #237 for that specifically

**Comment by nieomylnieja** [comment]
@BertHartm could please resolve the conflict? Thanks!

**Comment by BertHartm** [comment]
> @BertHartm could please resolve the conflict? Thanks!

updated, please review

**Comment by fourstepper** [comment]
I think that this ties into the discussion around Kubernetes compatibility a bit.

If we chose to use the Kubernetes [`ObjectMeta v1 meta`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#objectmeta-v1-meta), we would get this and more for free

**Comment by nieomylnieja** [comment]
@fourstepper, as discussed, let's merge it anyway and follow up with proposals of bringing metadata in sync with k8s metadata

**Pull request merged**
