### PR TITLE
Change AlertCondition.severity to optional, allow any string

### PR DESCRIPTION
**Pull request by nobl9-mikec**
## Summary 
- Updates `AlertCondition.severity` to be an optional field, and allow any string value

### Description
The concept of `severity` is likely to be varied across both AlertConditions and NotificationTargets.  The current implementation seems to act as a hint to the NotificationTarget about what type of notification should be sent (ticket or page), but it's likely that teams and services will have their own custom definitions of what `severity` means for a given alert breach or incident. 

For example, a team might using a numeric scaling of incident severity (Sev0, Sev1, Sev2) etc. with each severity level determining the course of notification action (Sev0 - page immediately and escalate in 5 min if unacked, Sev1 - page immediately and repeat every 30min unacked, etc.)

By decoupling the logic between AlertCondition severity and the type of Notification sent, the spec can be flexible enough to adapt to a wider variety of implementations and expectations. 

Other potential considerations would be moving the `severity` field to `AlertCondition.metadata` or potentially even `AlertCondition.metadata.labels`

### CODE REVIEW

**Comment by nobl9-mikec** [comment]
@weyert  Would love your feedback on this update!

**Comment by weyert** [comment]
Sounds fine to me, but I can imagine it could still be a required field? If it's required they have define a severity level (that could be `none`) and consider the severity?

**Comment by nobl9-mikec** [comment]
> Sounds fine to me, but I can imagine it could still be a required field? If it's required they have define a severity level (that could be none) and consider the severity?
It seems a little odd to support `none` on a required field, at that point is it really required? 
I think I'd prefer to keep it optional, some common alerting platforms (ex. [Grafana](https://grafana.com/docs/grafana/latest/alerting/old-alerting/create-alerts/)) don't have a built-in concept of `severity` and it feels odd to force it.  I'll ask around the Slack as well to see if other folks are interested in chiming in!

**Comment by proffalken** [comment]
I think most teams would have a concept of severity, and it certainly feels like something that should be part of best practice, because if everything is urgent then nothing has priority.

To @nobl9-mikec's point about Grafana, there could easily be a plugin or similar for Oslo that created the Grafana dashboards/alerts and just used different webhooks/alert configurations within Grafana depending on the value of this variable.

Leaving it as free-form text makes sense, as where some orgs use `Sev01` etc, others use `P1`, and others again `High` or `Urgent`, but I'd definitely be tempted to make it required.

**Comment by nobl9-mikec** [comment]
Awesome, thank you for the additional feedback @proffalken! 
Returning `severity` to `required` per based on you and @weyert's feedback

**Pull request merged**
