### PR TITLE
Make docs about Kind: Service less ambiguous

### LINKED ISSUE #23: Realtion of Services and SLOs not clear
It is not entirely clear that a service needs to be defined before you can apply that service to an SLO  in the documentation.

On the SLO Service attribute that should call that out, and on the Service part it should say what you do with the service string. Some people expect the service to be able to contain a list of SLOs, when in fact the relation is defined the other way.

### PR DESCRIPTION
**Pull request by programmer04**
Closes #23

### CODE REVIEW

**Review by davex98 — APPROVED** [review]
Good job! Thank you for clarifying this one

**Comment by kenfinnigan** [comment]
Does this change require Oslo validation to fail if an SLO exists without a `Service` kind object?

**Comment by proffalken** [comment]
Yup, looks good, but would want to be confident that @kenfinnigan's point about Oslo failing validation if this is not a valid object is in place.

Not sure if we'd want to merge the Oslo change or this one first?

**Comment by kenfinnigan** [comment]
I should've provided more context, as I was thinking of a slightly different problem.

Do we _really_ want to force users to create an empty `Service` kind to prevent Oslo from failing validation? For Workday, SLO documents aren't tied to Services in any way except by name. To force the creation of YAML to define a Service for a name lookup at first glance appears to be overkill, at least to me.

Is there a usage for having `Service` present I'm missing?

**Comment by programmer04** [comment]
So for  
```
# name of the service to associate this SLO with, refers to an existing object Kind: Service
```
instead of `refers` maybe I'll write `may refer (depends on implementation)`. What do you think @proffalken, @kenfinnigan?

**Comment by kenfinnigan** [comment]
I'm good with "may refer".

For the Service description, does it also need to change from "A Service is a high-level grouping of SLO. It has to be defined before creating SLO to be able to refer to it in SLO's `spec.service`." to use `may` instead of `has`?

**Comment by proffalken** [comment]
Yup, happy with that

**Comment by kenfinnigan** [comment]
Thanks @programmer04!

**Review by davex98 — APPROVED** [review]

**Pull request merged**
